# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version
import pandas as pd

##### set minimum snakemake version #####
min_version("7.16.0")


configfile: "config/config.yml"


samples = pd.read_csv(config["samples"], sep="\t").set_index("sample_id", drop=False)


include: "rules/ref.smk"
include: "rules/align.smk"


rule all:
    input:
        expand(
            rules.bwa_mem.output,
            outdir=config["outdir"],
            sample=samples["sample_id"],
        ),
