$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
    description: path to the output directory (does not need to exist)
  samples:
    type: string
    description: path to the runsheet
  genome:
    type: object
    description: genome information
    properties:
      ftp_fa:
        type: string
        description: ftp link to the genome fasta file
      name:
        type: string
        description: genome name
      ftp_gff:
        type: string
        description: ftp link to the gff file containing gene annotations
    required:
      - ftp_fa
      - name
      - ftp_gff

  retype:
    type:
      - array
      - string
    description: repeat type(s) to call
    enum:
      - L1
      - Alu
      - SVA
      - HERV
      - Mitochondrial

required:
  - samples
  - outdir
  - genome
  - reptype
