$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
    description: path to the output directory (does not need to exist)
  samples:
    type: string
    description: path to the runsheet
  genome:
    type: object
    description: information about the reference genome
    properties:
      region:
        type: string
      name:
        type: string
      fasta:
        type: string
    required:
      - name
      - region
      - fasta

  xtea_reptypes:
    type: array
    items:
      type: string
      enum:
        - L1
        - Alu
        - SVA
        - HERV
        - Mitochondrial
    description: repeat type(s) to call

required:
  - samples
  - outdir
  - genome
  - xtea_reptypes
